"""Add meal plans and planned meals

Revision ID: 46b6be8cebd2
Revises: b1c56da01da1
Create Date: 2026-10-03 18:55:51.690734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b6be8cebd2'
down_revision = 'b1c56da01da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('mealdb_id', sa.String(length=20), nullable=False),
    sa.Column('meal_name', sa.String(length=200), nullable=False),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_plan_id', 'day', name='unique_meal_plan_day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_meals')
    op.drop_table('meal_plans')
    # ### end Alembic commands ###
